# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_RPDFS_FS) += rpdfs.o

rpdfs-y	:= balloc.o \
           block.o \
	   btree.o \
	   btree_txn.o \
	   dir.o \
	   file.o \
	   inode.o \
	   map.o \
	   mkfs.o \
	   net.o \
	   net_tcp.o \
	   parse.o \
	   rht.o \
	   super.o \
	   txn.o \
	   xattr.o
